### PR TITLE
fix(driver/st_ltdc): Add missing lv_os_private.h include

### LINKED ISSUE #9190: lv_thread_sync_t not defined  in lv_st_ltdc.c when using FreeRTOS
### LVGL version

v9.4.0

### Platform

STM32F4 using LTDC and FreeRTOS

### What happened?

When compiling LVGL v9.4 (or master) with support for both the ST LTDC driver and an RTOS, the build fails.

The file `src/drivers/display/st_ltdc/lv_st_ltdc.c` uses the `lv_thread_sync_t` type when an OS is enabled, but it does not include the necessary private OSAL header where this type is defined.

### How to reproduce?

Configure LVGL to use both LTDC (LV_USE_ST_LTDC=1) and FreeRTOS (LV_USE_OS   LV_OS_FREERTOS), compilation will fail here
https://github.com/lvgl/lvgl/blob/9c05fce72ba886b4dc200d1791015e82c1100808/src/drivers/display/st_ltdc/lv_st_ltdc.c#L37
with the error `unknown type name 'lv_thread_sync_t'`.

This appears to be a regression introduced in PR #8889, where OSAL types were moved to the `lv_os_private.h` header.

### PR DESCRIPTION
**Pull request by timohueser**
Fixes #9190 

This PR resolves a compilation error in the ST LTDC driver (`lv_st_ltdc.c`) that occurs when `LV_USE_OS` is set to `LV_OS_FREERTOS`.

The driver uses `lv_thread_sync_t`, but the required header (`osal/lv_os_private.h`) where this private OSAL type is defined was missing. This PR adds the missing include.

### Notes
- Update the [Documentation](https://github.com/lvgl/lvgl/tree/master/docs) if needed.
- Add [Examples](https://github.com/lvgl/lvgl/tree/master/examples) if relevant.
- Add [Tests](https://github.com/lvgl/lvgl/blob/master/tests/README.md) if applicable.
- If you added new options to `lv_conf_template.h` run [lv_conf_internal_gen.py](https://github.com/lvgl/lvgl/blob/master/scripts/lv_conf_internal_gen.py) and update [Kconfig](https://github.com/lvgl/lvgl/blob/master/Kconfig).
- Run `scripts/code-format.py` (`astyle v3.4.12` needs to installed by running `cd scripts; ./install_astyle.sh`) and follow the [Code Conventions](https://docs.lvgl.io/master/CODING_STYLE.html).
- Mark the Pull request as [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) while you are working on the first version, and mark is as _Ready_ when it's ready for review.
- When changes were requested, [re-request review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to notify the maintainers.
- Help us to review this Pull Request! Anyone can [approve or request changes](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews).

### CODE REVIEW

**Review by AndreCostaaa — APPROVED** [review]

**Review by uLipe — APPROVED** [review]

**Comment by carlo-dev-git** [comment]
Is there a plan to roll this fix back to 9.4? A new 9.4.1 release could be very helpful if something stopped compiling starting in 9.4.0.
