### PR TITLE
fix(thorvg): fix compilation on thread-less platforms

### LINKED ISSUE #8362: ThorVG: Compilation failure on thread-less targets
### LVGL version

9.3.0

### Platform

STM32H7 with ARM GNU Toolchain arm-none-eabi 13.2 using nano.specs (_newlib-nano_)

### What happened?

`using` statements in [tvgTaskScheduler.h](https://github.com/lvgl/lvgl/blob/c033a98afddd65aaafeebea625382a94020fe4a7/src/libs/thorvg/tvgTaskScheduler.h#L36) results in the following compiler error:

```
lvgl/src/libs/thorvg/tvgTaskScheduler.h:36:12: error: 'mutex' has not been declared in 'std'
   36 | using std::mutex;
      |            ^~~~~
lvgl/src/libs/thorvg/tvgTaskScheduler.h:37:12: error: 'condition_variable' has not been declared in 'std'
   37 | using std::condition_variable;
      |            ^~~~~~~~~~~~~~~~~~
```

`std::mutex` and `std::condition_variable` are usually not available/not applicable on MCU targets.

Concerned changes introduced in #8043 

### How to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by technophil98**
Only if `THORVG_THREAD_SUPPORT` is defined, conditionally include `<mutex>`, `<condition_variable>`, and `<thread>` along with the related `using` statements.

Fixes: #8362

### CODE REVIEW

**Review by FASTSHIFT — APPROVED** [review]

**Comment by AndreCostaaa** [comment]
Is `tvgTaskScheduler` necessary on thread-less platforms ?

Wouldn't it make more sense to wrap the whole file in `#ifdef THORVG_THREAD_SUPPORT` ?

**Comment by technophil98** [comment]
> Is `tvgTaskScheduler` necessary on thread-less platforms ?
> 
> Wouldn't it make more sense to wrap the whole file in `#ifdef THORVG_THREAD_SUPPORT` ?

A simplified `Task` struct defined in `tvgTaskScheduler` is used in these files:

- tvgInitializer.cpp
- tvgLottieLoader.h
- tvgLottieModel.cpp
- tvgSvgLoader.h
- tvgSvgSceneBuilder.cpp
- tvgSwRenderer.cpp
- tvgTaskScheduler.cpp

It looks like "tvgTaskScheduler.h" is required without `THORVG_THREAD_SUPPORT` and cannot be fully ifdef'd.

**Review by AndreCostaaa — APPROVED** [review]
Of course... Sorry, had to scroll further down to see it

Thanks for the fix :100:

**Comment by technophil98** [comment]
> Of course... Sorry, had to scroll further down to see it

No worries! Thanks for the review 😄
