### ISSUE TITLE
Unable to build with ESPIDF 6.0.0 usig PlatformIO

### ISSUE THREAD

**Issue by fixiwurm** [lvgl/lvgl#10049]
### LVGL version

9.5.0

### Platform

PlatformIO using the following configuration:

```[env:waveshare_oled]
platform = espressif32 @ ^7.0.0


board                       = esp32-s3-devkitc-1
framework                   = espidf

board_build.flash_mode      = qio
board_build.psram_type      = opi
board_upload.flash_size     = 16MB
board_upload.maximum_size   = 16777216

build_flags =
    -D LV_CONF_SKIP
    -D LV_COLOR_DEPTH=16
    -D LV_USE_LOG=1
    -D LV_FONT_MONTSERRAT_24=1

lib_deps =
    lvgl/lvgl @ ^9.5.0 
```

### What happened?

No matter what i try, i get the following error
`cc1plus: warning: command-line option '-Wno-old-style-declaration' is valid for C/ObjC but not for C++`

setting CONFIG_COMPILER_WARNINGS_AS_ERRORS to false results in a buch of the following issues:
``` /home/XXX/.platformio/packages/toolchain-xtensa-esp-elf/lib/gcc/xtensa-esp-elf/15.2.0/include/stddef.h:229: Error: unknown opcode or format name 'typedef'
/home/XXX/.platformio/packages/toolchain-xtensa-esp-elf/lib/gcc/xtensa-esp-elf/15.2.0/include/stddef.h:344: Error: unknown opcode or format name 'typedef'
/home/XXX/.platformio/packages/framework-espidf/components/esp_libc/platform_include/sys/reent.h:31: Error: unknown opcode or format name 'struct'
/home/XXX/.platformio/packages/framework-espidf/components/esp_libc/platform_include/sys/reent.h:34: Error: unknown opcode or format name 'int'
/home/XXX/.platformio/packages/framework-espidf/components/esp_libc/platform_include/sys/reent.h:35: Error: unknown opcode or format name 'int' 
 ```

Due to other issues I was unable to try an older ESP IDF version. Any help would be appreciated! 

### How to reproduce?

Create an empty PlatformIO project, past the configuration, and try to compile the project. I tested it on my machine, with a clean setup, and found that the issue is reproducible.

**Comment by blink7** [comment]
Same here with PlatformIO + ESP-IDF 6.0.1.
Interestingly, it builds completely fine in a pure ESP-IDF project (w/o PlatformIO), so this is definitely a PlatformIO build system integration issue.

**Comment by david-sharer** [comment]
For anyone else that stumbles across this...

I ran into this as well, previously. Using VSCode PlatformIO extension under Windows 11.

As a result of investigating this then, I found that ESP-IDF integration with PlatformIO was outdated by default (?) and possibly required a third party repo for maybe-better support. (Which I can't find now...)
So I opted to try the ESP-IDF toolkit directly.

This completely failed on Windows despite several attempts.
This is apparently a well-known issue, despite me being unable to find any resolution.
So I decided to finally give Linux another go as a daily driver OS.
Everything there worked without issue.

I used ESP-IDF toolchain directly (via VSCodium extensions) - under linux (bazzite) within a distrobox.
I believe I also had to construct the distrobox with some flags to allow USB communication.

**Comment by blink7** [comment]
> So I opted to try the ESP-IDF toolkit directly.
> This completely failed on Windows despite several attempts.

Just to share another perspective, I actually managed to set up the ESP-IDF environment on Windows without any issues using the official ESP-IDF Installation Manager.
​It works flawlessly and builds perfectly.

**Comment by FelixWurm** [comment]
> > So I opted to try the ESP-IDF toolkit directly.
> > This completely failed on Windows despite several attempts.
> 
> Just to share another perspective, I actually managed to set up the ESP-IDF environment on Windows without any issues using the official ESP-IDF Installation Manager. ​It works flawlessly and builds perfectly.

I also switched from PlatformIO to ESP-IDF. I think the problem has to have something to do with an incompatibility between C and C++ (as in PlatformIO wants to use C++, but LVGL is made for C). For now the combination PlatformIO+EPS32+LVGL seems to be broken.

**Comment by embedim** [comment]
try use  idf_component.yml and remove from .ini

```
dependencies:
  lvgl/lvgl: "^9.5.0"
```

**Comment by AndreCostaaa** [comment]
Hi @fbiego could you take a look at this one whenever you get a chance?
